name: Quality

on: [push]

jobs:
  ESLint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy config
        run: cp example.config.json config.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint . --max-warnings=0

  dprint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run dprint
        run: npx dprint check

  TypeScript:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy config
        run: cp example.config.json config.json

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript
        run: npx tsc --noEmit

  CSpell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: streetsidesoftware/cspell-action@v8
